services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: postgres
    volumes:
      - ./src:/app/src
    command: yarn dev

  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
